image: local-registry.inner.buaaoo.top/image-dev/java:8u201

stages:
  - build
  - test

before_script:
  - java -version
  - javac -version
  - mvn -v
  - tree -a .

mvn_build:
  stage: build
  script:
    - echo "Build project"
    - mvn compile
  artifacts:
    expire_in: 2 hrs
    paths:
      - target

mvn_test:
  stage: test
  dependencies:
    - mvn_build
  script:
    - tree -a .
    - echo "Run JUnit4"
    - mvn cobertura:cobertura
    - mvn cobertura:dump-datafile
  coverage: '/coverage line-rate="\d+/'
  artifacts:
    expire_in: 2 hrs
    paths:
      - target